---
- hosts: digitalocean
  tasks:
  - name: "Deploy SSH key to DO"
    digital_ocean_sshkey:
      state: present
      name: "Public Key"
      oauth_token: "{{ do.api_token }}"
      ssh_pub_key: "{{ ssh_pub_key }}"
    register: key

  - name: "Create droplet"
    digital_ocean:
      state: present
      command: droplet
      name: "{{ do.droplet.name }}"
      size_id: "{{ do.droplet.size_id }}"
      region_id: "{{ do.droplet.region  }}"
      image_id: "{{ do.droplet.image_id }}"
      backups_enabled: "{{ do.droplet.backups_enabled  }}"
      api_token: "{{ do.api_token }}"
      ssh_key_ids: "{{ key.data.ssh_key.id }}"
      wait_timeout: 500
      unique_name: true
      ipv6: false
    register: do_droplet

  - name: "Gather ssh public key"
    command: "ssh-keyscan -t ecdsa {{ do_droplet.droplet.ip_address }}"
    register: ssh_keyscan_public_key
    when: do_droplet.changed

  - name: "Add VM public key to known hosts"
    known_hosts:
      name: "{{ do_droplet.droplet.ip_address }}"
      key: "{{ item }}"
    with_items: "{{ ssh_keyscan_public_key.stdout_lines }}"
    when: do_droplet.changed

  - name: "Try ssh on default port"
    command: "nc -z {{ do_droplet.droplet.ip_address }} 22"
    register: default_port_login_attempt
    failed_when: no

  - name: "Set custom ssh port"
    set_fact: ssh_custom_port="{{ security.ssh.custom_port }}"
    when: default_port_login_attempt.rc != 0

  - name: "Add droplet to inventory"
    add_host:
      name: "{{ do_droplet.droplet.name }}"
      groups: "droplet"
      ansible_host: "{{ do_droplet.droplet.ip_address }}"
      ansible_python_interpreter: "/usr/bin/python3"
      ansible_user: root
      ansible_port: " {{ ssh_custom_port | default(22) | int }}"

