---
- hosts: droplet
  tasks:

  - name: "baildon.co"
    block:
    - name: "Clone baildon.co"
      git:
        repo: "https://github.com/sBaildon/baildon.co.git"
        dest: "{{ droplet.serve.root_path }}/baildon.co"

    - name: "Make baildon.co"
      make:
        chdir: "{{ droplet.serve.root_path }}/baildon.co"
    become: yes
    become_user: "{{ droplet.users.unprivileged.name }}"

  - name: "ui.baildon.co"
    block:
    - name: "Clone ui.baildon.co"
      git:
        repo: "https://github.com/sBaildon/ui.baildon.co.git"
        dest: "{{ droplet.serve.root_path }}/ui.baildon.co"
      become: yes
      become_user: "{{ droplet.users.unprivileged.name }}"

    - name: "Install ImageMagick"
      dnf:
        name: ImageMagick

    - name: "Install jq"
      dnf:
        name: jq

    - name: "Make ui.baildon.co"
      make:
        chdir: "{{ droplet.serve.root_path }}/ui.baildon.co"
      become: yes
      become_user: "{{ droplet.users.unprivileged.name }}"

  - name: "{{ startup.name }}"
    block:
    - name: "Clone {{ startup.name }}"
      git:
        repo: "git@gitlab.com:sBaildon/{{ startup.repo_name }}.git"
        dest: "{{ droplet.serve.root_path }}/{{ startup.repo_name }}"
        key_file: "/home/{{ droplet.users.unprivileged.name }}/.ssh/id_rsa"
        accept_hostkey: yes
    - name: "Make {{ startup.name }}"
      make:
        chdir: "{{ droplet.serve.root_path }}/{{ startup.repo_name }}"
    become: yes
    become_user: "{{ droplet.users.unprivileged.name }}"

  - name: "snakeway"
    block:
    - name: "Clone snakeway"
      git:
        repo: "git@gitlab.com:sBaildon/snakeway.git"
        dest: "{{ droplet.serve.root_path }}/dev1.baildon.co"

    - name: "Make snakeway"
      make:
        chdir: "{{ droplet.serve.root_path }}/snakeway"

    become: yes
    become_user: "{{ droplet.users.unprivileged.name }}"

  - name: "Start caddy"
    systemd:
      name: caddy
      daemon_reload: yes
      enabled: yes
      state: restarted
