---
- hosts: vps
  tasks:

  - name: "Add github known host"
    command: "ssh-keyscan -H github.com"
    register: github_keyscan_public_key

  - name: "Add github public key to unpriviliged users known hosts"
    known_hosts:
      name: "github.com"
      key: "{{ item }}"
    with_items: "{{ github_keyscan_public_key.stdout_lines }}"
    become: yes
    become_user: "{{ users.unprivileged.name }}"

  - name: "baildon.co"
    block:
    - name: "Clone baildon.co"
      git:
        repo: "https://github.com/sbaildon/baildon.co.git"
        dest: "{{ serve.root_path }}/baildon.co"
      become: yes
      become_user: "{{ users.unprivileged.name }}"

    - name: "Install g++"
      dnf:
        name: gcc-c++

    - name: "Make baildon.co"
      make:
        chdir: "{{ serve.root_path }}/baildon.co"
      become: yes
      become_user: "{{ users.unprivileged.name }}"

  - name: "ui.baildon.co"
    block:
    - name: "Clone ui.baildon.co"
      git:
        repo: "https://github.com/sbaildon/ui.baildon.co.git"
        dest: "{{ serve.root_path }}/ui.baildon.co"
      become: yes
      become_user: "{{ users.unprivileged.name }}"

    - name: "Install ImageMagick"
      dnf:
        name: ImageMagick

    - name: "Install jq"
      dnf:
        name: jq

    - name: "Make ui.baildon.co"
      make:
        chdir: "{{ serve.root_path }}/ui.baildon.co"
      become: yes
      become_user: "{{ users.unprivileged.name }}"

  - name: "Start caddy"
    systemd:
      name: caddy
      daemon_reload: yes
      enabled: yes
      state: restarted
