---
- hosts: droplet
  tasks:

  - name: "Add github known host"
    command: "ssh-keyscan -H github.com"
    register: github_keyscan_public_key

  - name: "Add VM public key to known hosts"
    known_hosts:
      name: "github.com"
      key: "{{ item }}"
    with_items: "{{ github_keyscan_public_key.stdout_lines }}"
    become: yes
    become_user: "{{ droplet.users.unprivileged.name }}"

  - name: "baildon.co"
    block:
    - name: "Clone baildon.co"
      git:
        repo: "https://github.com/sBaildon/baildon.co.git"
        dest: "{{ droplet.serve.root_path }}/baildon.co"
      become: yes
      become_user: "{{ droplet.users.unprivileged.name }}"

    - name: "Install g++"
      dnf:
        name: gcc-c++

    - name: "Make baildon.co"
      make:
        chdir: "{{ droplet.serve.root_path }}/baildon.co"
      become: yes
      become_user: "{{ droplet.users.unprivileged.name }}"

  - name: "ui.baildon.co"
    block:
    - name: "Clone ui.baildon.co"
      git:
        repo: "https://github.com/sBaildon/ui.baildon.co.git"
        dest: "{{ droplet.serve.root_path }}/ui.baildon.co"
      become: yes
      become_user: "{{ droplet.users.unprivileged.name }}"

    - name: "Install ImageMagick"
      dnf:
        name: ImageMagick

    - name: "Install jq"
      dnf:
        name: jq

    - name: "Make ui.baildon.co"
      make:
        chdir: "{{ droplet.serve.root_path }}/ui.baildon.co"
      become: yes
      become_user: "{{ droplet.users.unprivileged.name }}"

  - name: "snakeway"
    block:
    - name: "Clone snakeway"
      git:
        repo: "git@github.com:sbaildon/snakeway.git"
        dest: "{{ droplet.serve.root_path }}/snakeway"

    - name: "Make snakeway"
      make:
        chdir: "{{ droplet.serve.root_path }}/snakeway"

    become: yes
    become_user: "{{ droplet.users.unprivileged.name }}"

  - name: "agency"
    block:
    - name: "Clone agency"
      git:
        repo: "git@github.com:sbaildon/twitch-agency.git"
        dest: "{{ droplet.serve.root_path }}/agency"

    - name: "Make agency"
      make:
        chdir: "{{ droplet.serve.root_path }}/agency"

    become: yes
    become_user: "{{ droplet.users.unprivileged.name }}"

  - name: "Start caddy"
    systemd:
      name: caddy
      daemon_reload: yes
      enabled: yes
      state: restarted
