---
- hosts: vps

  tasks:
  - name: "Install firewalld"
    dnf:
      name: firewalld

  - name: "Enable and start firewalld"
    systemd:
      name: firewalld
      enabled: yes
      state: started

  - name: "Allow https traffic"
    firewalld:
      service: https
      permanent: yes
      state: enabled

  - name: "Allow http traffic"
    firewalld:
      service: http
      permanent: yes
      state: enabled

  - name: "Allow ssh traffic"
    firewalld:
      service: ssh
      permanent: yes
      state: enabled

  - name: "Allow custom ssh traffic"
    firewalld:
      port: "{{ security.ssh.custom_port }}/tcp"
      permanent: yes
      state: enabled

  - name: "Enable firewalld changes"
    systemd:
      name: firewalld
      state: restarted
