---
- hosts: vps

  tasks:
  - name: "Create pihole container"
    shell: "{{ lookup('file', '../resources/pihole/setup.sh') }}"
    args:
      executable: "/bin/bash"
    failed_when: no
    register: container_created

  - name: "create pihole service file"
    shell:
      cmd: "podman generate systemd pihole > /etc/systemd/system/pihole.service"
    when: container_created.rc == 0

  - name: "Allow dns traffic"
    firewalld:
      service: dns
      permanent: yes
      state: enabled

  - name: "Enable firewalld changes"
    systemd:
      name: firewalld
      state: restarted

  - name: "Start pihole"
    systemd:
      name: pihole
      daemon_reload: yes
      enabled: yes
      state: started
