---
- hosts: droplet

  tasks:
  - name: "Install firewalld"
    dnf:
      name: firewalld

  - name: "Enable and start firewalld"
    systemd:
      name: firewalld
      enabled: yes
      state: started

  - name: "Create new zone"
    firewalld:
      zone: "{{ security.firewalld.zone_name }}"
      permanent: true
      state: present
    register: new_zone

  - name: "Reload firewalld config to enable new zone"
    systemd:
      name: firewalld
      state: reloaded
    when: new_zone.changed

  - name: "Assign new zone to interface"
    firewalld:
      zone: "{{ security.firewalld.zone_name }}"
      interface: eth0
      permanent: true
      state: enabled

  - name: "Allow https traffic"
    firewalld:
      zone: "{{ security.firewalld.zone_name }}"
      service: https
      permanent: true
      state: enabled

  - name: "Allow http traffic"
    firewalld:
      zone: "{{ security.firewalld.zone_name }}"
      service: http
      permanent: true
      state: enabled

  - name: "Allow ssh traffic"
    firewalld:
      zone: "{{ security.firewalld.zone_name }}"
      service: ssh
      permanent: true
      state: enabled

  - name: "Allow custom ssh traffic"
    firewalld:
      zone: "{{ security.firewalld.zone_name }}"
      port: "{{ security.ssh.custom_port }}/tcp"
      permanent: true
      state: enabled

  - name: "Enable firewalld changes"
    systemd:
      name: firewalld
      state: restarted

  - name: "Change SSH port"
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: 'Port\s\d'
      line: "Port {{ security.ssh.custom_port }}"

  - name: "Disallow root login"
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin.*$'
      line: 'PermitRootLogin no'

  - name: "Disallow password login"
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^[#]?PasswordAuthentication.*$'
      line: 'PasswordAuthentication no'

  - name: "Restart sshd"
    systemd:
      name: sshd
      enabled: yes
      state: restarted
