---
- hosts: vps
  tasks:

  - name: "Perform dnf upate"
    dnf:
      name: "*"
      state: latest

  - name: "Install vim-enhanced"
    dnf:
      name: vim-enhanced

  - name: "Install golang"
    dnf:
      name: golang

  - name: "Install docker-ce"
    block:
    - name: "Add docker-ce-stable repository"
      yum_repository:
        name: docker-ce
        description: "Docker CE Stable"
        baseurl: "https://download.docker.com/linux/fedora/$releasever/$basearch/stable"
        gpgcheck: yes
        gpgkey: "https://download.docker.com/linux/fedora/gpg"

    - name: "Install docker-ce"
      dnf:
        name: docker-ce

  - name: "Install wireguard"
    block:
    - name: "Add wireguard repository"
      yum_repository:
        name: "wireguard"
        description: "Copr repo for wireguard owned by jdoss"
        baseurl: "https://copr-be.cloud.fedoraproject.org/results/jdoss/wireguard/epel-7-$basearch/"
        gpgcheck: yes
        gpgkey: "https://copr-be.cloud.fedoraproject.org/results/jdoss/wireguard/pubkey.gpg"
    - name: "Install wireguard packages"
      dnf:
        name: ['wireguard-dkms', 'wireguard-tools']

  - name: "Install docker-py"
    pip:
      name: docker-py
      extra_args: --user

  - name: "Enable and start docker"
    systemd:
      name: docker
      enabled: yes
      state: started

  - name: "Install tmux"
    dnf:
      name: tmux

  - name: "Install git"
    dnf:
      name: git

  - name: "Install tree"
    dnf:
      name: tree

  - name: "Install wget"
    dnf:
      name: wget

  - name: "Install nodejs"
    dnf:
      name: nodejs

  - name: "Install yarn"
    block:
    - name: "Add yarn repository"
      yum_repository:
        name: yarn
        description: yarn
        baseurl: "https://dl.yarnpkg.com/rpm/"
        gpgcheck: yes
        gpgkey: "https://dl.yarnpkg.com/rpm/pubkey.gpg"
    - name: "Install yarn"
      dnf:
        name: yarn
