---
- hosts: vps
  tasks:

  - name: "Perform dnf upate"
    dnf:
      name: "*"
      state: latest

  - name: "Install vim-enhanced"
    dnf:
      name: "vim-enhanced"

  - name: "Install ripgrep"
    dnf:
      name: "ripgrep"

  - name: "Install fd"
    dnf:
      name: "fd-find"

  - name: "Install podman"
    dnf:
      name: podman

  - name: "Install tmux"
    dnf:
      name: tmux

  - name: "Install git"
    dnf:
      name: git

  - name: "Install tree"
    dnf:
      name: tree

  - name: "Install wget"
    dnf:
      name: wget

  - name: "Install make"
    dnf:
      name: make

  - name: "Install nodejs"
    dnf:
      name: nodejs

  - name: "Install yarn"
    block:
    - name: "Add yarn repository"
      yum_repository:
        name: yarn
        description: yarn
        baseurl: "https://dl.yarnpkg.com/rpm/"
        gpgcheck: yes
        gpgkey: "https://dl.yarnpkg.com/rpm/pubkey.gpg"
    - name: "Install yarn"
      dnf:
        name: yarn
