---
- hosts: droplet

  vars_prompt:
  - name: "personal_password"
    prompt: "Enter password for personal user"
    private: yes
    encrypt: "sha256_crypt"
    confirm: yes
    salt_size: 7

  tasks:
  - name: "Add docker group"
    group:
      name: docker
      state: present

  - name: "Add personal user"
    user:
      name: "{{ droplet.users.personal.name }}"
      password: "{{ personal_password }}"
      update_password: "on_create"
      generate_ssh_key: true
      ssh_key_bits: 4096
      ssh_key_comment: "{{ droplet.users.personal.name }}@$HOSTNAME"
      groups:
        - docker
        - wheel

  - name: "Add ssh-key for personal user"
    authorized_key:
      user: "{{ droplet.users.personal.name }}"
      state: present
      key: "{{ ssh_pub_key }}"

  - name: "Add unprivileged user"
    user:
      name: "{{ droplet.users.unprivileged.name }}"
      generate_ssh_key: true
      ssh_key_bits: 4096
      ssh_key_comment: "{{ droplet.users.unprivileged.name }}@$HOSTNAME"

  - name: "Read unprivileged user's public ssh key"
    slurp:
      src: "/home/{{ droplet.users.unprivileged.name }}/.ssh/id_rsa.pub"
    register: unprivileged_pub_ssh_key

  - name: "Deploy unprivileged user key to github"
    uri:
      url: "https://api.github.com/user/keys"
      method: POST
      status_code: 200,201,400,422
      body:
        title: "{{ droplet.users.unprivileged.name }}-auto-provision"
        key: "{{ unprivileged_pub_ssh_key.content | b64decode }}"
      body_format: json
      headers:
        Authorization: "token {{ github_token }}"

  - name: "SELinux permissive"
    selinux:
      policy: targeted
      state: permissive
