---
- hosts: machine

  tasks:
  - name: "Install dependencies"
    dnf:
      name: ["kernel-devel", "kernel-headers", "python3-firewall"]
    register: deps

  - name: "reboot"
    reboot:
    when: deps.changed

  - name: "wait for reboot"
    wait_for:
      host: "{{ machine.ip_address }}"
    when: deps.changed

  - debug:
      msg: "Maybe you'll need to install kernel first, then wg, then reboot"

  - name: "Enable net.ipv4.ip_forward"
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      reload: yes
      state: present

  - name: "Enable masquerading"
    firewalld:
      zone: "{{ security.firewalld.zone_name }}"
      masquerade: yes
      permanent: true
      state: enabled

  - name: "Create wireguard directory"
    file:
      path: /etc/wireguard
      state: directory

  - name: "Generate private keys"
    shell: wg genkey
    register: wireguard_genkey
    changed_when: false

  - set_fact:
      private_key: "{{ wireguard_genkey.stdout }}"

  - name: "Generate public keys"
    shell: "echo {{ private_key }} | wg pubkey"
    register: wireguard_pubkey
    changed_when: false

  - set_fact:
      public_key: "{{ wireguard_pubkey.stdout }}"

  - debug:
      msg: "Public key {{ public_key }}"

  - name: "Configure wireguard"
    template:
      src: ../templates/wg0.conf.j2
      dest: /etc/wireguard/wg0.conf
      owner: root
      group: root
      mode: 600

  - name: "Start wireguard"
    systemd:
      name: "wg-quick@wg0"
      enabled: yes
      state: restarted

  - name: "Create new zone"
    firewalld:
      zone: "wgvpn"
      permanent: true
      state: present
    register: new_zone

  - name: "Reload firewalld config to enable new zone"
    systemd:
      name: firewalld
      state: reloaded
    when: new_zone.changed

  - name: "Assign new zone to interface"
    firewalld:
      zone: "wgvpn"
      interface: wg0
      permanent: true
      state: enabled

  - name: "Allow inital setup wireguard traffic"
    firewalld:
      zone: "{{ security.firewalld.zone_name }}"
      port: "51820/udp"
      permanent: true
      state: enabled

  - name: "Enable firewalld changes"
    systemd:
      name: firewalld
      state: restarted
