---
- hosts: vps

  tasks:
  - name: "Install wireguard"
    dnf:
      name: wireguard-tools

  - name: "Create wireguard directory"
    file:
      path: /etc/wireguard
      state: directory
      mode: 0755

  - name: "Generate private key"
    shell:
      chdir: "/etc/wireguard/"
      cmd: "wg genkey | tee private_key"
      creates: "/etc/wireguard/private_key"
    register: wireguard_genkey

  - name: "Set private key mode"
    file:
      state: file
      mode: 0600
      path: "/etc/wireguard/private_key"
    when: wireguard_genkey.changed

  - name: "Read private key"
    slurp:
      src: "/etc/wireguard/private_key"
    register: slurped_private_key

  - set_fact:
      private_key: "{{ slurped_private_key.content | b64decode }}"

  - name: "Generate public key"
    shell:
      chdir: "/etc/wireguard/"
      cmd: "cat /etc/wireguard/private_key | wg pubkey | tee public_key"
      creates: "/etc/wireguard/public_key"
    register: public_key

  - debug:
      msg: "Public key {{ public_key.stdout }}"
    when: public_key.changed

  - name: "Deploy network interface file"
    copy:
      src: "../resources/wireguard/wg0.network"
      dest: "/etc/systemd/network/wg0.network"
      mode: 0600
      owner: "systemd-network"
      group: "systemd-network"

  - name: "Deploy netdev file"
    template:
      src: "../resources/wireguard/wg0.netdev.j2"
      dest: "/etc/systemd/network/wg0.netdev"
      mode: 0600
      owner: "systemd-network"
      group: "systemd-network"

  - name: "Enable net.ipv4.ip_forward"
    sysctl:
      name: net.ipv4.ip_forward
      value: "1"
      reload: yes
      state: present

  - name: "Enable ipv6 forwarding"
    sysctl:
      name: net.ipv6.conf.all.forwarding
      value: "1"
      reload: yes
      state: present

  - name: "Enable public masquerading"
    firewalld:
      zone: "public"
      masquerade: "yes"
      permanent: true
      state: enabled
      immediate: yes

  - name: "Assign wireguard interface to internal"
    firewalld:
      zone: "internal"
      interface: wg0
      permanent: true
      state: enabled

  - name: "Enable internal masquerading"
    firewalld:
      zone: "internal"
      masquerade: "yes"
      permanent: true
      state: enabled
      immediate: yes

  - name: "Add wireguard service to firewalld"
    copy:
      src: "../resources/wireguard/wireguard.xml"
      dest: "/etc/firewalld/services/wireguard.xml"
      mode: 0600

  - name: "Enable firewalld changes"
    systemd:
      name: firewalld
      state: restarted

  - name: "Allow wireguard traffic"
    firewalld:
      zone: "public"
      service: "wireguard"
      permanent: true
      state: enabled
      immediate: yes

  - name: "Restart network"
    systemd:
      name: systemd-networkd
      enabled: yes
      state: restarted
