---
- hosts: vps

  tasks:
  - debug:
      msg: "Maybe you'll need to install kernel first, then wg, then reboot"

  - name: "Enable net.ipv4.ip_forward"
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      reload: yes
      state: present

  - name: "Enable ipv6 forwarding"
    sysctl:
      name: net.ipv6.conf.all.forwarding
      value: 1
      reload: yes
      state: present

  - name: "Enable masquerading"
    firewalld:
      zone: "{{ security.firewalld.zone_name }}"
      masquerade: yes
      permanent: true
      state: enabled

  - name: "Create wireguard directory"
    file:
      path: /etc/wireguard
      state: directory

  - name: "Generate private keys"
    shell: wg genkey
    register: wireguard_genkey
    changed_when: false

  - set_fact:
      private_key: "{{ wireguard_genkey.stdout }}"

  - name: "Generate public keys"
    shell: "echo {{ private_key }} | wg pubkey"
    register: wireguard_pubkey
    changed_when: false

  - set_fact:
      public_key: "{{ wireguard_pubkey.stdout }}"

  - debug:
      msg: "Public key {{ public_key }}"

  - name: "Configure wireguard"
    template:
      src: ../templates/wg0.conf.j2
      dest: /etc/wireguard/wg0.conf
      owner: root
      group: root
      mode: 600

  - name: "Start wireguard"
    systemd:
      name: "wg-quick@wg0"
      enabled: yes
      state: restarted

  - name: "Set wireguard interface as trusted"
    firewalld:
      zone: "trusted"
      interface: wg0
      permanent: true
      state: enabled

  - name: "Allow inital setup wireguard traffic"
    firewalld:
      zone: "{{ security.firewalld.zone_name }}"
      port: "51820/udp"
      permanent: true
      state: enabled

  - name: "Enable firewalld changes"
    systemd:
      name: firewalld
      state: restarted
